#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MASTER_CHILDS 4
#define NUM_PROCESSES 3

#define SHMOBJ_PATH "/shm_server"
#define SEM_PATH "/sem_server"

#define MAX_SHM_SIZE 1024
#define SHM_OFFSET_POSITION 0
#define SHM_OFFSET_FORCE_COMPONENTS 100

#define SEED_MULTIPLIER 120
#define MAX_NUMBER 50
#define MAX_STRING_LEN 100

#define SIMULATION_WIDTH 500
#define SIMULATION_HEIGHT 500

#endif // !CONSTANTS_H
